
# lines = ["Chateau Haut Brion	2019  ",
# "Chateau Latour	2012  ",
# "Château Margaux 	2019  ",
# "Chateau Mouton Rothschild	2019  ",
# "Chateau Lafite Rothschild	2019  ",
# "Château Ausone	2019  ",
# "Chateau Angélus	2019  ",
# "Chateau Angélus	2015  ",
# "Chateau Cheval Blanc	2019  ",
# "Château Pavie 	2016  ",
# "Chateau Pavie	2019  ",
# "Les Hauts de Smith 	2020 alb ",
# "Chateau Smith Haut Lafitte	2019 alb ",
# "Chateau Smith Haut Lafitte	2020 alb ",
# "Domaine de Chevalier	2018 alb ",
# "Chateau Pape Clement	2020 alb ",
# "Prelat de Pape Clement	2019 alb ",
# "Clos La Gaffeliere 	2019  ",
# "Chateau Laroque	2019  ",
# "Chateau Poesia	2019  ",
# "Chateau Lassegue	2019  ",
# "Chateau Fleur Cardinale 	2019  ",
# "Chateau Grand Mayne 	2019  ",
# "Clos Rene 	2015  ",
# "Chateau La Cabanne 	2019  ",
# "La Fleur Petrus	2016  ",
# "La Fleur Petrus	2018  ",
# "Chateau La Fleur De Bouard - Lalande de Pomerol	2019  ",
# "Chateau d'Issan 	2019  ",
# "Malescot Saint Exupery 	2019  ",
# "Château Giscours 	2019  ",
# "Sirène de Giscours	2019  ",
# "Chateau La Gurgue - Margaux	2019  ",
# "Domaine de Chevalier rouge	2019  ",
# "Chateau Smith Haut Lafitte 	2019  ",
# "Chateau Pape Clement 	2019  ",
# "Chateau Malartic Lagravière 	2019  ",
# "Cos d'Estournel - Saint-Estèphe	2016  ",
# "Le Marquis de Calon Segur 	2019  ",
# "Chateau Phelan Segur 	2019  ",
# "Calon Ségur	2019  ",
# "Chateau Clerc Milon - Pauillac	2019  ",
# "Chateau Haut Bages Liberal - Pauillac	2019  ",
# "Le Petit Mouton de Mouton Rothschild - Pauillac	2019  ",
# "Clerc Milon	2019  ",
# "Lynch Bages	2019  ",
# "Grand Puy Lacoste	2019  ",
# "Chateau Pontet Canet	2019  ",
# "Chateau Gloria 	2019  ",
# "Croix Ducru Beaucaillou 	2019  ",
# "Ducru Beaucaillou	2019  ",
# "Branaire Ducru	2019  ",
# "Léoville Poyferré	2019  ",
# "Langoa Barton	2019  ",
# "Léoville Barton	2019  ",
# "Chateau D'Yquem	2003  ",
# ]
lines = ["Chateau Haut Brion	  ",
"Chateau Latour	  ",
"Château Margaux 	  ",
"Chateau Mouton Rothschild	  ",
"Chateau Lafite Rothschild	  ",
"Château Ausone	  ",
"Chateau Angélus	  ",
"Chateau Angélus	  ",
"Chateau Cheval Blanc	  ",
"Château Pavie 	  ",
"Chateau Pavie	  ",
"Les Hauts de Smith 	  ",
"Chateau Smith Haut Lafitte	  ",
"Chateau Smith Haut Lafitte	  ",
"Domaine de Chevalier	  ",
"Chateau Pape Clement	  ",
"Prelat de Pape Clement	  ",
"Clos La Gaffeliere 	  ",
"Chateau Laroque	  ",
"Chateau Poesia	  ",
"Chateau Lassegue	  ",
"Chateau Fleur Cardinale 	  ",
"Chateau Grand Mayne 	  ",
"Clos Rene 	  ",
"Chateau La Cabanne 	  ",
"La Fleur Petrus	  ",
"La Fleur Petrus	  ",
"Chateau La Fleur De Bouard - Lalande de Pomerol	  ",
"Chateau d'Issan 	  ",
"Malescot Saint Exupery 	  ",
"Château Giscours 	  ",
"Sirène de Giscours	  ",
"Chateau La Gurgue - Margaux	  ",
"Domaine de Chevalier rouge	  ",
"Chateau Smith Haut Lafitte 	  ",
"Chateau Pape Clement 	  ",
"Chateau Malartic Lagravière 	  ",
"Cos d'Estournel - Saint-Estèphe	  ",
"Le Marquis de Calon Segur 	  ",
"Chateau Phelan Segur 	  ",
"Calon Ségur	  ",
"Chateau Clerc Milon - Pauillac	  ",
"Chateau Haut Bages Liberal - Pauillac	  ",
"Le Petit Mouton de Mouton Rothschild - Pauillac	  ",
"Clerc Milon	  ",
"Lynch Bages	  ",
"Grand Puy Lacoste	  ",
"Chateau Pontet Canet	  ",
"Chateau Gloria 	  ",
"Croix Ducru Beaucaillou 	  ",
"Ducru Beaucaillou	  ",
"Branaire Ducru	  ",
"Léoville Poyferré	  ",
"Langoa Barton	  ",
"Léoville Barton	  ",
"Chateau D'Yquem	  ",
]